Resources:
  Bad:
    Type: 'AWS::Glue::DataCatalogEncryptionSettings'
    Properties:
      CatalogId: "CatalogId"
      DataCatalogEncryptionSettings:
        ConnectionPasswordEncryption:
          KmsKeyId: "KmsKeyId"
          ReturnConnectionPasswordEncrypted: True