Resources:
  Bad:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNUsers
      PolicyDocument:
        Statement:
          - Action:
              - s3:HeadBucket
              - '*'
            Effect: Allow
            Resource:
              - arn:aws:s3:::b1
              - arn:aws:s3:::b1/*
            Sid: ''
        Version: '2012-10-17'
      Groups:
        - !Ref 'CFNUserGroup'
